name: "Run Tests and Upload Coverage"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby environment
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    # Step 4: Run tests with SimpleCov for coverage
    - name: Run tests and generate coverage
      run: |
        bundle exec rspec

    # Step 5: Upload coverage to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/.resultset.json
        token: ${{ secrets.CODECOV_TOKEN }}
